### ISSUE TITLE
Map handling

### ISSUE THREAD

**Issue by jtmoulia** [massemanet/distel#46] opened 2015-03-05 06:18 UTC
R17 saw the introduction of maps, and I just checked -- they're supported by the erlang distribution protocol. They're a great addition, and it would be swell for distel to support them.

I can work on this, but I'm not sure what the best translation for an erlang map would be -- an emacs hash-table?

Thanks in advance

**Comment by massemanet** [comment] 2018-08-13 14:01
dupe of #47

**Closed by massemanet** 2018-08-13 14:01 UTC
